services:
  yci107-er-lev1:
    build: .
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    env_file:
      - .env
    restart: always

    networks:
      - yci107_network

networks:
  yci107_network:
    external: true
