[project]
name = "yci107-er-lev1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pip>=25.2",
    "uvicorn>=0.35.0",
]
